import { validationError, type ValidationIssue } from "./appErrors";
import {
  defaultSettings,
  type AIChatRequest,
  type AIInsightResponse,
  type AppSettings,
  type BrandingSettings,
  type MarketingTargets,
  type ProjectPayload,
  type StandardField,
  standardFields
} from "./types";

export type PdfExportPayload = {
  title: string;
  dateRange?: string;
  analysis: ProjectPayload["analysis"];
  aiInsights?: AIInsightResponse | null;
  branding: BrandingSettings;
};

export function assertProjectId(id: unknown): string {
  if (typeof id !== "string" || !/^[a-zA-Z0-9_-]{8,128}$/.test(id)) {
    throw validationError([{ field: "id", message: "Invalid workspace identifier." }]);
  }
  return id;
}

export function validateProjectPayload(input: unknown): ProjectPayload {
  const record = asRecord(input);
  const issues: ValidationIssue[] = [];
  const name = cleanText(record.name, 160);
  const originalFileName = cleanText(record.originalFileName, 240);
  const cleanedRows = Array.isArray(record.cleanedRows) ? record.cleanedRows.slice(0, 250_000) : [];
  const analysis = record.analysis as ProjectPayload["analysis"] | undefined;
  const columnMapping = asRecord(record.columnMapping) as ProjectPayload["columnMapping"];
  const dateRangeStart = cleanDate(record.dateRangeStart, "dateRangeStart", issues);
  const dateRangeEnd = cleanDate(record.dateRangeEnd, "dateRangeEnd", issues);

  if (!name) issues.push({ field: "name", message: "Workspace name is required." });
  if (!originalFileName) issues.push({ field: "originalFileName", message: "Original file name is required." });
  if (!cleanedRows.length) issues.push({ field: "cleanedRows", message: "Analyze at least one campaign row before saving." });
  if (!analysis?.overall || !Array.isArray(analysis.campaigns)) issues.push({ field: "analysis", message: "A completed campaign analysis is required." });
  validateMapping(columnMapping, issues);

  const id = optionalId(record.id, "id", issues);
  if (issues.length) throw validationError(issues);

  return {
    id,
    name,
    clientName: cleanText(record.clientName, 160),
    platform: cleanText(record.platform, 80),
    dateRangeStart,
    dateRangeEnd,
    originalFileName,
    cleanedRows: cleanedRows as ProjectPayload["cleanedRows"],
    columnMapping,
    analysis: analysis as ProjectPayload["analysis"],
    aiInsights: record.aiInsights ? (record.aiInsights as ProjectPayload["aiInsights"]) : null
  };
}

export function validateSettings(input: unknown, secureStorageAvailable = true): AppSettings {
  const record = asRecord(input);
  const issues: ValidationIssue[] = [];
  const targets = validateTargets(record.targets, issues);
  const brandingRecord = asRecord(record.branding);
  const aiProvider = ["openai", "anthropic", "disabled"].includes(String(record.aiProvider)) ? (record.aiProvider as AppSettings["aiProvider"]) : "disabled";
  const apiKey = typeof record.apiKey === "string" && record.apiKey.trim() ? record.apiKey.trim() : undefined;

  if (apiKey && !secureStorageAvailable) {
    issues.push({
      field: "apiKey",
      message: "Secure key storage is unavailable on this system. Use an environment variable or disable AI."
    });
  }

  if (issues.length) throw validationError(issues);

  return {
    aiProvider,
    apiKey,
    hasStoredApiKey: Boolean(record.hasStoredApiKey),
    model: cleanText(record.model, 120) || (aiProvider === "anthropic" ? "claude-3-5-haiku-latest" : "gpt-4o-mini"),
    targets,
    branding: {
      companyName: cleanText(brandingRecord.companyName, 120) || "GrowthLens AI",
      analystName: cleanText(brandingRecord.analystName, 120),
      clientName: cleanText(brandingRecord.clientName, 120),
      primaryColor: sanitizeBrandColor(brandingRecord.primaryColor),
      reportFooter: cleanText(brandingRecord.reportFooter, 240) || "Generated by GrowthLens Campaign",
      logoPath: typeof brandingRecord.logoPath === "string" ? cleanText(brandingRecord.logoPath, 500) : undefined
    },
    defaultCurrency: cleanText(record.defaultCurrency, 12).toUpperCase() || "USD",
    dateFormat: cleanText(record.dateFormat, 40) || "Auto",
    defaultAttributionField: cleanText(record.defaultAttributionField, 80) || "conversions",
    allowDetailedAiData: Boolean(record.allowDetailedAiData)
  };
}

export function validatePdfExportPayload(input: unknown): PdfExportPayload {
  const record = asRecord(input);
  const issues: ValidationIssue[] = [];
  const title = cleanText(record.title, 160) || "GrowthLens Campaign Executive Brief";
  const analysis = record.analysis as ProjectPayload["analysis"] | undefined;

  if (!analysis?.overall || !Array.isArray(analysis.campaigns)) {
    issues.push({ field: "analysis", message: "A completed campaign analysis is required before export." });
  }
  if (issues.length) throw validationError(issues);

  return {
    title,
    dateRange: cleanText(record.dateRange, 120),
    analysis: analysis as ProjectPayload["analysis"],
    aiInsights: record.aiInsights ? (record.aiInsights as AIInsightResponse) : null,
    branding: validateSettings({ ...defaultSettings, branding: record.branding }, true).branding
  };
}

export function validateAiInsightPayload(input: unknown): { targets: MarketingTargets; analysis: ProjectPayload["analysis"]; cleanedRows?: ProjectPayload["cleanedRows"]; allowDetailedAiData?: boolean } {
  const record = asRecord(input);
  const issues: ValidationIssue[] = [];
  const targets = validateTargets(record.targets, issues);
  const analysis = record.analysis as ProjectPayload["analysis"] | undefined;
  const cleanedRows = Array.isArray(record.cleanedRows) ? (record.cleanedRows.slice(0, 250_000) as ProjectPayload["cleanedRows"]) : undefined;
  if (!analysis?.overall || !Array.isArray(analysis.campaigns)) {
    issues.push({ field: "analysis", message: "A completed campaign analysis is required." });
  }
  if (issues.length) throw validationError(issues);
  return { targets, analysis: analysis as ProjectPayload["analysis"], cleanedRows, allowDetailedAiData: Boolean(record.allowDetailedAiData) };
}

export function validateAiChatRequest(input: unknown): AIChatRequest {
  const record = asRecord(input);
  const issues: ValidationIssue[] = [];
  const targets = validateTargets(record.targets, issues);
  const analysis = record.analysis as ProjectPayload["analysis"] | undefined;
  const question = cleanText(record.question, 4_000);
  const projectId = optionalId(record.projectId, "projectId", issues) ?? null;
  const sessionId = optionalId(record.sessionId, "sessionId", issues) ?? null;
  const cleanedRows = Array.isArray(record.cleanedRows) ? (record.cleanedRows.slice(0, 250_000) as ProjectPayload["cleanedRows"]) : undefined;

  if (!question) {
    issues.push({ field: "question", message: "Ask the AI Analyst a question before sending." });
  }
  if (typeof record.question === "string" && record.question.length > 4_000) {
    issues.push({ field: "question", message: "Keep AI Analyst questions under 4,000 characters." });
  }
  if (!analysis?.overall || !Array.isArray(analysis.campaigns)) {
    issues.push({ field: "analysis", message: "Run a completed campaign analysis before using AI Analyst Chat." });
  }
  if (issues.length) throw validationError(issues);

  return {
    projectId,
    sessionId,
    question,
    analysis: analysis as ProjectPayload["analysis"],
    targets,
    aiInsights: record.aiInsights ? (record.aiInsights as AIInsightResponse) : null,
    cleanedRows,
    allowDetailedAiData: Boolean(record.allowDetailedAiData)
  };
}

export function sanitizeBrandColor(value: unknown, fallback = "#1E1B4B"): string {
  return typeof value === "string" && /^#[0-9a-fA-F]{6}$/.test(value.trim()) ? value.trim() : fallback;
}

function validateTargets(value: unknown, issues: ValidationIssue[]): MarketingTargets {
  const record = asRecord(value);
  const targetRoas = numberInRange(record.targetRoas, 0, 100, defaultSettings.targets.targetRoas, "targetRoas", issues);
  const minimumCtr = numberInRange(record.minimumCtr, 0, 1, defaultSettings.targets.minimumCtr, "minimumCtr", issues);
  const minimumConversionRate = numberInRange(record.minimumConversionRate, 0, 1, defaultSettings.targets.minimumConversionRate, "minimumConversionRate", issues);
  return {
    targetRoas,
    targetCpa: optionalNumber(record.targetCpa, 0, 1_000_000, "targetCpa", issues),
    minimumCtr,
    maximumCpc: optionalNumber(record.maximumCpc, 0, 1_000_000, "maximumCpc", issues),
    minimumConversionRate,
    profitMargin: optionalNumber(record.profitMargin, 0, 1, "profitMargin", issues)
  };
}

function validateMapping(mapping: ProjectPayload["columnMapping"], issues: ValidationIssue[]): void {
  const valid = new Set<string>(standardFields);
  for (const key of Object.keys(mapping)) {
    if (!valid.has(key)) {
      issues.push({ field: "columnMapping", message: `Unknown mapping field: ${key}.` });
    }
  }
  for (const required of ["campaign_name", "impressions", "clicks", "spend"] satisfies StandardField[]) {
    if (!mapping[required]) {
      issues.push({ field: `columnMapping.${required}`, message: `${required.replace(/_/g, " ")} is required.` });
    }
  }
}

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value) ? (value as Record<string, unknown>) : {};
}

function cleanText(value: unknown, maxLength: number): string {
  return typeof value === "string" ? value.replace(/\s+/g, " ").trim().slice(0, maxLength) : "";
}

function optionalId(value: unknown, field: string, issues: ValidationIssue[]): string | undefined {
  if (value === undefined || value === null || value === "") return undefined;
  if (typeof value !== "string" || !/^[a-zA-Z0-9_-]{8,128}$/.test(value)) {
    issues.push({ field, message: "Invalid identifier." });
    return undefined;
  }
  return value;
}

function cleanDate(value: unknown, field: string, issues: ValidationIssue[]): string | undefined {
  if (value === undefined || value === null || value === "") return undefined;
  if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value) || Number.isNaN(Date.parse(`${value}T00:00:00Z`))) {
    issues.push({ field, message: "Use YYYY-MM-DD format." });
    return undefined;
  }
  return value;
}

function optionalNumber(value: unknown, min: number, max: number, field: string, issues: ValidationIssue[]): number | null {
  if (value === undefined || value === null || value === "") return null;
  return numberInRange(value, min, max, null, field, issues);
}

function numberInRange(value: unknown, min: number, max: number, fallback: number, field: string, issues: ValidationIssue[]): number;
function numberInRange(value: unknown, min: number, max: number, fallback: null, field: string, issues: ValidationIssue[]): number | null;
function numberInRange(value: unknown, min: number, max: number, fallback: number | null, field: string, issues: ValidationIssue[]): number | null {
  const parsed = Number(value);
  if (!Number.isFinite(parsed) || parsed < min || parsed > max) {
    issues.push({ field, message: `Enter a value between ${min} and ${max}.` });
    return fallback;
  }
  return parsed;
}
